firstName         = "#first-name"
lastName          = "#last-name"
postalCode        = "#postal-code"
continueButton    = "#continue"
cancelButton      = "#cancel"
finishButton      = "#finish"
checkoutComplete  = "h2.complete-header"