homeHeader = "css=span.title"
itemOne   = "#add-to-cart-sauce-labs-backpack"
itemTwo   = "#add-to-cart-sauce-labs-bike-light"
itemThree = "#add-to-cart-sauce-labs-bolt-t-shirt"
itemFour  = "#add-to-cart-sauce-labs-fleece-jacket"
itemFive  = "#add-to-cart-sauce-labs-onesie"
itemSix   = "#add-to-cart-test.allthethings()-t-shirt-(red)"
cartLink = "css=a.shopping_cart_link"
 
removeItemOne   = "#remove-sauce-labs-backpack"
removeItemTwo   = "#remove-sauce-labs-bike-light"
removeItemThree = "#remove-sauce-labs-bolt-t-shirt"
removeItemFour  = "#remove-sauce-labs-fleece-jacket"
removeItemFive  = "#remove-sauce-labs-onesie"
removeItemSix   = "#remove-test.allthethings()-t-shirt-(red)"